/*
WRITE THE QUERY TO CREATE PRODUCT TAB;LE EITH 6 COLUMN 
1.PID NUMBER PRIMARY KEY
2.PNAME VARCHAER(30)
3.PRICE NUMBER CHECK(PRICE>0)
4.MDATE DATE
5.EDATE DATE
6.DISCOUNT VARCHAR(10)


CREATE TABLE PRODUCT(
    PID NUMBER PRIMARY KEY,
    PNAME VARCHAR(20),
    PPRICE NUMBER CHECK(PPRICE>0),
    MDATE DATE ,
    EDATE DATE,
    DISC VARCHAR(4)
);

*/

/* WRITE A PROGRAM TO CREATE CUSTOMER TABLE
1.CID NUMBER PRIMARY KEY 
2.CNAME VARCHAR(30),
3.DOB DATE,
4.ADHAR NUMBER CHECK(LENGTH(ADHAR)=12)
5.PAN CHAR(10)
6.ADDRESS VARCHAR(30)*/
CREATE TABLE  CUSTOMER
(
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR(30),
    DOB DATE,
    ADHARNO CHECK(LENGTH(ADHARNO)=12),
    PAN  CHAR(10),
    ADDRESS VARCHAR(40)
);