select SAL
from EMP1
WHERE SAL IN (SELECT MAX(SAL) FROM EMP1
WHERE SAL > ALL (SELECT MAX(SAL)FROM EMP1 WHERE SAL>
 ALL (SELECT MAX(SAL)FROM EMP1 WHERE SAL
>ALL (SELECT MAX(SAL)FROM EMP1))));

-- 201) .WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
SELECT DNAME FROM DEPT WHERE DEPTNO IN 
(SELECT DEPTNO FROM EMP1 WHERE ENAME LIKE '%A%');

-- 202) . WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS
-- SALARY IS RUPEES 800. 

SELECT DNAME,LOC FROM DEPT WHERE DEPTNO IN 
(SELECT DEPTNO FROM EMP1 WHERE SAL=800);

-- 203) .WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME FROM DEPT WHERE DEPTNO IN 
(SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL );

SELECT *FROM EMP1;
SELECT *FROM DEPT;

-- 204) .WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40
SELECT LOC FROM DEPT WHERE DEPTNO IN 
(SELECT DEPTNO FROM EMP WHERE 
COMM IS NOT NULL AND DEPTNO=40);


-- 205) .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME FROM EMP1 WHERE JOB IN
(SELECT JOB FROM EMP1 WHERE JOB='SALESMAN');