---CASE2---

CREATE TABLE DEPT (
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');

COMMIT;


CREATE TABLE EMP1 (
    EMPNO    NUMBER(4) PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2),
    
    CONSTRAINT FK_EMP_DEPT
    FOREIGN KEY (DEPTNO)
    REFERENCES DEPT(DEPTNO)
);

INSERT INTO EMP1 VALUES
(7369, 'SMITH', 'CLERK', 7902,
 TO_DATE('17-DEC-80','DD-MON-RR'), 800, NULL, 20);

INSERT INTO EMP1 VALUES
(7499, 'ALLEN', 'SALESMAN', 7698,
 TO_DATE('20-FEB-81','DD-MON-RR'), 1600, 300, 30);

INSERT INTO EMP1 VALUES
(7521, 'WARD', 'SALESMAN', 7698,
 TO_DATE('22-FEB-81','DD-MON-RR'), 1250, 500, 30);

INSERT INTO EMP1 VALUES
(7566, 'JONES', 'MANAGER', 7839,
 TO_DATE('02-APR-81','DD-MON-RR'), 2975, NULL, 20);

INSERT INTO EMP1 VALUES
(7654, 'MARTIN', 'SALESMAN', 7698,
 TO_DATE('28-SEP-81','DD-MON-RR'), 1250, 1400, 30);

INSERT INTO EMP1 VALUES
(7698, 'BLAKE', 'MANAGER', 7839,
 TO_DATE('01-MAY-81','DD-MON-RR'), 2850, NULL, 30);

INSERT INTO EMP1 VALUES
(7782, 'CLARK', 'MANAGER', 7839,
 TO_DATE('09-JUN-81','DD-MON-RR'), 2450, NULL, 10);

INSERT INTO EMP1 VALUES
(7788, 'SCOTT', 'ANALYST', 7566,
 TO_DATE('19-APR-87','DD-MON-RR'), 3000, NULL, 20);

INSERT INTO EMP1 VALUES
(7839, 'KING', 'PRESIDENT', NULL,
 TO_DATE('17-NOV-81','DD-MON-RR'), 5000, NULL, 10);

INSERT INTO EMP1 VALUES
(7844, 'TURNER', 'SALESMAN', 7698,
 TO_DATE('08-SEP-81','DD-MON-RR'), 1500, 0, 30);

INSERT INTO EMP1 VALUES
(7876, 'ADAMS', 'CLERK', 7788,
 TO_DATE('23-MAY-87','DD-MON-RR'), 1100, NULL, 20);

INSERT INTO EMP1 VALUES
(7900, 'JAMES', 'CLERK', 7698,
 TO_DATE('03-DEC-81','DD-MON-RR'), 950, NULL, 30);

INSERT INTO EMP1 VALUES
(7902, 'FORD', 'ANALYST', 7566,
 TO_DATE('03-DEC-81','DD-MON-RR'), 3000, NULL, 20);

INSERT INTO EMP1 VALUES
(7934, 'MILLER', 'CLERK', 7782,
 TO_DATE('23-JAN-82','DD-MON-RR'), 1300, NULL, 10);

COMMIT;
select * from EMP1;
select * from DEPT ;

---186).WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH ---
SELECT DNAME from DEPT where DEPTNO
 IN (SELECT DEPTNO FROM EMP1 WHERE ENAME='SMITH');

---.WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING---
SELECT DNAME,LOC FROM DEPT WHERE DEPTNO =(SELECT DEPTNO FROM EMP1 WHERE ENAME='KING');
---188).WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902---

SELECT LOC FROM DEPT WHERE DEPTNO =(SELECT DEPTNO FROM EMP1 WHERE EMPNO=7902);

---.WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT


SELECT DNAME FROM DEPT WHERE DEPTNO 
IN (SELECT DEPTNO FROM EMP1 WHERE JOB='PRESIDENT' );

---191) .WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT---

SELECT ENAME FROM EMP1 WHERE DEPTNO 
=(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');


---192) .WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO---

SELECT ENAME ,SAL FROM EMP1 WHERE DEPTNO IN
 (SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');


---193). WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES--- 


 SELECT * FROM EMP1 WHERE DEPTNO 
=(SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

---94).WAQTD DETAILS OF THE EMP ALONG WITH ANNUA SALARY IF EMPLOYEES ARE WORKING IN NEW YORK---

SELECT EMP1.*, SAL*12 AS "ANNUALSALARY" FROM EMP1 
WHERE DEPTNO IN
 (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

 ---195) .WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT---

SELECT ENAME FROM EMP1 WHERE DEPTNO IN
(SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');

---195) .WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT---
 
SELECT ENAME FROM EMP1 WHERE SAL > 
(SELECT SAL FROM EMP1 WHERE ENAME='SCOTT') AND DEPTNO IN
(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

---196). WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO ---

SELECT * FROM EMP1 WHERE JOB='MANAGER' AND DEPTNO IN 
(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO');

---WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING---
SELECT ENAME,SAL FROM EMP1 WHERE SAL >
(SELECT SAL FROM EMP1 WHERE ENAME='KING') AND DEPTNO IN 
(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');

---WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES ---
SELECT * FROM EMP1 WHERE JOB='SALESMAN' AND 
DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME='SALES');

---WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING ---
SELECT ENAME,SAL,JOB, HIREDATE FROM EMP1 WHERE  HIREDATE < 
(SELECT HIREDATE FROM EMP1 WHERE ENAME='KING')
 AND DEPTNO IN 
(SELECT DEPTNO FROM DEPT WHERE DNAME='OPERATIONS');

---200) .DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.---
SELECT * FROM EMP1 WHERE DEPTNO IN(SELECT DEPTNO FROM DEPT WHERE DNAME LIKE '%S');