CREATE TABLE STUDENT1 
(
    STUDENT_ID     NUMBER PRIMARY KEY,
    STUDENT_NAME   VARCHAR2(15),
    GENDER         VARCHAR2(6),
    DEPARTMENT     VARCHAR2(15),
    YEAR_OF_STUDY NUMBER,
    MARKS          NUMBER,
    CITY           VARCHAR2(15),
    ADMDATE DATE
);

INSERT INTO STUDENT1 VALUES (101, 'AMIT',   'MALE',   'COMPUTER',    1, 78, 'DELHI',       DATE '2023-07-01');
INSERT INTO STUDENT1 VALUES (102, 'RIYA',   'FEMALE', 'COMPUTER',    2, 85, 'MUMBAI',      DATE '2022-06-15');
INSERT INTO STUDENT1 VALUES (103, 'KARAN',  'MALE',   'MECHANICAL',  3, 65, 'PUNE',        DATE '2021-08-20');
INSERT INTO STUDENT1 VALUES (104, 'NEHA',   'FEMALE', 'ELECTRICAL',  4, 90, 'DELHI',       DATE '2020-07-10');
INSERT INTO STUDENT1 VALUES (105, 'RAHUL',  'MALE',   'COMPUTER',    2, 55, 'CHENNAI',     DATE '2022-06-18');
INSERT INTO STUDENT1 VALUES (106, 'SNEHA',  'FEMALE', 'MECHANICAL',  1, 88, 'BANGALORE',   DATE '2023-07-05');
INSERT INTO STUDENT1 VALUES (107, 'ARJUN',  'MALE',   'ELECTRICAL',  3, 72, 'HYDERABAD',   DATE '2021-08-25');
INSERT INTO STUDENT1 VALUES (108, 'POOJA',  'FEMALE', 'COMPUTER',    4, 95, 'MUMBAI',      DATE '2020-07-12');
INSERT INTO STUDENT1 VALUES (109, 'VIKAS',  'MALE',   'CIVIL',       2, 60, 'JAIPUR',      DATE '2022-06-22');
INSERT INTO STUDENT1 VALUES (110, 'ANJALI', 'FEMALE', 'CIVIL',       1, 82, 'DELHI',       DATE '2023-07-08');
INSERT INTO STUDENT1 VALUES (111, 'ROHIT',  'MALE',   'COMPUTER',    3, 68, 'NOIDA',       DATE '2021-08-18');
INSERT INTO STUDENT1 VALUES (112, 'KAVYA',  'FEMALE', 'ELECTRICAL',  2, 91, 'CHENNAI',     DATE '2022-06-10');
INSERT INTO STUDENT1 VALUES (113, 'MOHIT',  'MALE',   'MECHANICAL',  4, 74, 'PUNE',        DATE '2020-07-20');
INSERT INTO STUDENT1 VALUES (114, 'NIDHI',  'FEMALE', 'COMPUTER',    1, 89, 'GURGAON',     DATE '2023-07-02');
INSERT INTO STUDENT1 VALUES (115, 'SANJAY', 'MALE',   'CIVIL',       3, 58, 'BHOPAL',      DATE '2021-08-30');
INSERT INTO STUDENT1 VALUES (116, 'PRIYA',  'FEMALE', 'MECHANICAL',  2, 76, 'INDORE',     DATE '2022-06-25'); 
 
 select *from STUDENT1;

 COMMIT ; 

-- Write a query to display all columns from the STUDENT table using *.
-- Write a query to display complete student details.
-- Write a query to display every record and column from STUDENT.
-- Write a query to display full data of the STUDENT table.
-- Write a query to display student information exactly as stored.
select *from STUDENT1; 


-- Write a query to display all columns and MARKS + 5 as BONUS_MARKS.
SELECT STUDENT1.*, MARKS +5 AS BONUS_MARKS
FROM STUDENT1;

-- Write a query to display all student details and MARKS * 2 as DOUBLE_MARKS.
SELECT STUDENT1.*, MARKS * 2 AS DOUBLE_MARKS
FROM STUDENT1;

-- Write a query to display all columns along with YEAR_OF_STUDY + 1 as NEXT_YEAR.
SELECT STUDENT1.*,YEAR_OF_STUDY + 1 as NEXT_YEAR FROM STUDENT1;