CREATE TABLE CUSTOMER
(
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR(20) ,
    CADDRESS VARCHAR(50),
    CMNO NUMBER CHECK(LENGTH(CMNO)=10),
    CEMAIL VARCHAR(20) UNIQUE
);


INSERT INTO  CUSTOMER VALUES (01,'SHRUTI','PUNE',2345512433,'shruti@gmail.com');
INSERT INTO  CUSTOMER VALUES (02,'RUTUJA','DELHI',2346713333,'rutuja@gmail.com');
INSERT INTO  CUSTOMER VALUES (03,'POOJA','HYDRABAD',2345512358,'pooja@gmail.com');
INSERT INTO  CUSTOMER VALUES (04,'ARTI','NAGPUR',2345511111,'arti@gmail.com');
commit;
SELECT *FROM CUSTOMER;


CREATE TABLE ORDERS
(
    OID NUMBER PRIMARY KEY,
    OTIME VARCHAR(6),
    ODATE DATE ,
    CID NUMBER ,
    CONSTRAINT OR_FK FOREIGN KEY(CID) REFERENCES CUSTOMER(CID)
);

INSERT INTO  ORDERS VALUES (001,'04.05',SYSDATE,01);
INSERT INTO  ORDERS VALUES (002,'02.05',SYSDATE,02);
INSERT INTO  ORDERS VALUES (003,'04.05',SYSDATE,03);
INSERT INTO  ORDERS VALUES (004,'10.05',SYSDATE,04);
commit;
SELECT *FROM ORDERS;

CREATE TABLE MENUS
(
   MID NUMBER PRIMARY KEY,
   MITEM VARCHAR(20),
   PRICE NUMBER,
   CONTENT VARCHAR(60),
   OID NUMBER,
   CONSTRAINT ME_FK FOREIGN KEY(OID) REFERENCES ORDERS(OID)
);

INSERT INTO  MENUS VALUES (1,'IDLI',70,'PROTEIENS,VITAMINS,FATS ',02);
INSERT INTO  MENUS VALUES (2,'UPMA',30,'PROTEINS,VITAMINS,FATS',01);
INSERT INTO  MENUS VALUES (3,'POHA',35,'PROTEIENS,VITAMINS,FATS ',04);
INSERT INTO  MENUS VALUES (4,'SAMOSA',45,'PROTEIENS,VITAMINS,FATS ',03);
commit;
SELECT *FROM MENUS;

CREATE TABLE PAYMENT(
    PID NUMBER PRIMARY KEY,
    PMODE VARCHAR(20),
    PAMOUNT VARCHAR(10),
    STATUSS VARCHAR(10),
    PDATE DATE,
    OID NUMBER,
    CONSTRAINT PT_FK FOREIGN KEY(OID) REFERENCES ORDERS(OID)
);

INSERT INTO  PAYMENT VALUES (01,'CASH ON DELIVERY',70,'PRNDING',SYSDATE,002);
INSERT INTO  PAYMENT VALUES (02,'PHONEPAY',30,'PREPAID',SYSDATE,001);
INSERT INTO  PAYMENT VALUES (03,'GPAY',35,'PREPAID',SYSDATE,004);
INSERT INTO  PAYMENT VALUES (04,'CARD',45,'PREPAID',SYSDATE,003);
commit;
SELECT *FROM PAYMENT;