/*Create Table COURSE1(
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR(30),
    FEES NUMBER CHECK(FEES>0),
    DURATION NUMBER CHECK(DURATION<=12)
     
);
*/
Create Table student1(
    SID NUMBER PRIMARY KEY,
    SNAME VARCHAR(30),
    MNO NUMBER CHECK(LENGTH(MNO)=10),
    DOB DATE,
    PAN CHAR(10) CHECK(LENGTH(PAN)=10),
    CID NUMBER,
    CONSTRAINT CID_FK1 FOREIGN KEY(CID) REFERENCES COURSE1(CID)
     
);
/*
CREATE TABLE TRAINER1(
    TID NUMBER,
    TNAME VARCHAR(20),
    MNO NUMBER CHECK(LENGTH(MNO)=10),
    DOB DATE,
    DOJ DATE,
    SAL NUMBER CHECK(SAL>0),
    CID NUMBER,
    CONSTRAINT CID_FK2 FOREIGN KEY(CID) REFERENCES COURSE1(CID)
);

CREATE TABLE PAYMENT1(
    PID NUMBER,
    AMOUNT NUMBER CHECK(AMOUNT>=0),
    STATUS VARCHAR(20),
    PAYMODE VARCHAR(20),
    PDATE DATE,
    PRODATE DATE,
    SID NUMBER,
    CONSTRAINT SID_FK1 FOREIGN KEY(SID) REFERENCES student1(SID)


);

CREATE TABLE ATTENDANCE
(
    ADATE DATE ,
    STATUS VARCHAR(20) ,
    BATCHCODE VARCHAR(30),
    SID NUMBER ,
    CONSTRAINT SID_FK2 FOREIGN KEY (SID) REFERENCES student1(SID)
);

SELECT *FROM COURSE1;
DESCRIBE COURSE1

INSERT INTO COURSE1 VALUES(101,'PYD',30000,7);
INSERT INTO COURSE1 VALUES(102,'JFD',35000,9);
COMMIT;
INSERT INTO COURSE1 VALUES(103,'MSD',45000,8);
INSERT INTO COURSE1 VALUES(104,'TESTING',45000,5);
*/
SELECT *FROM student1;
DESCRIBE student1;

INSERT INTO student1 VALUES(1,'PRIYA',3005614892,SYSDATE,'AB345AT84E',102);
INSERT INTO student1 VALUES(2,'JYOTI',3504684100,SYSDATE,'GH2457YF83',103);

INSERT INTO student1 VALUES(3,'MOHIT',4501475800,SYSDATE,'GH784BH3B4',104);
INSERT INTO student1 VALUES(4,'TRISHA',4450985000,SYSDATE,'BKJ485JN4N',101);

COMMIT;