Create Table COURSE1(
    CID NUMBER PRIMARY KEY,
    CNAME VARCHAR(30),
    FEES NUMBER CHECK(FEES>0),
    DURATION NUMBER CHECK(DURATION<=12)
     
);

Create Table student1(
    SID NUMBER PRIMARY KEY,
    SNAME VARCHAR(30),
    MNO NUMBER CHECK(LENGTH(MNO)=10),
    DOB DATE,
    PAN CHAR(10) CHECK(LENGTH(PAN)=10),
    CID NUMBER,
    CONSTRAINT CID_FK1 FOREIGN KEY(CID) REFERENCES COURSE1(CID)
     
);

CREATE TABLE TRAINER1(
    TID NUMBER,
    TNAME VARCHAR(20),
    MNO NUMBER CHECK(LENGTH(MNO)=10),
    DOB DATE,
    DOJ DATE,
    SAL NUMBER CHECK(SAL>0),
    CID NUMBER,
    CONSTRAINT CID_FK2 FOREIGN KEY(CID) REFERENCES COURSE1(CID)
);

CREATE TABLE PAYMENT1(
    PID NUMBER,
    AMOUNT NUMBER CHECK(AMOUNT>=0),
    STATUS VARCHAR(20),
    PAYMODE VARCHAR(20),
    PDATE DATE,
    PRODATE DATE,
    SID NUMBER,
    CONSTRAINT SID_FK1 FOREIGN KEY(SID) REFERENCES student1(SID)


);

CREATE TABLE ATTENDANCE
(
    ADATE DATE ,
    STATUS VARCHAR(20) ,
    BATCHCODE VARCHAR(30),
    SID NUMBER ,
    CONSTRAINT SID_FK2 FOREIGN KEY (SID) REFERENCES student1(SID)
);